version: '3'
services:
  redis:
    image: 'redis:3.2.11'
    ports:
      - '6379:6379'
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8008:8008'
    env_file:
      - .env
    depends_on:
      - redis
